### ISSUE TITLE
Retnet parameter dimension

### ISSUE THREAD

**Issue by allanj** [microsoft/torchscale#57]
I wonder why we need twice dimensions for $\mathbf{W}_V$

<img width="991" alt="image" src="https://github.com/microsoft/torchscale/assets/3351187/4c7ef857-288a-44fa-9b55-6ae92c06b786">

**Comment by Yuxin-CV** [comment]
Please note that the MSR block includes an additional swish gate compared to the MHSA block in the vanilla Transformer. If we do not double the dimension of v, the MSR block will have 5d^2 parameters, while the MHSA block in the vanilla Transformer only has 4d^2 parameters. Given this scenario, it becomes challenging to determine the width and depth of a retnet for fair comparison with a baseline vanilla Transformer of the same size. Therefore, the authors decide to double the value of W_v and halve the value of d_ffn to maintain the overall parameters of each retnet block equal to 12d^2.

Alternatively, another option is to keep W_v the same as W_k and set d_ffn to 3.5d. However, it is preferable to have a wider swish gate rather than a wider feed-forward network (ffn). For more details, please refer to https://arxiv.org/abs/2202.10447.

**Comment by allanj** [comment]
Cool, pretty much makes sense to me. Thanks for the thorough explanationa.
